# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: vP5lm1hosr7NhrUpH0rC1dcyzVYFKO8t
            client-secret: S6OMf1RI_Z7LwL15BK9XKoLsaaK-VucCzBj38KqMsPKDY0-H3ZD68mTud0iBnlO0
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important! trae el dominio que tenemos cuando se creo el proyecto en Auth0
            issuer-uri: https://dev-83czcgd4.us.auth0.com/